[book]
authors = ["Rageking8"]
language = "en"
multilingual = false
src = "source"
title = "Planar Engine"

[output.html]
no-section-label = true
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = true
